wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      4: 3.7.10
      5: 0.10.26
      8:
      - 1
      - 5
